### ISSUE TITLE
Processing assets does not respect rate limits

### ISSUE THREAD

**Issue by lwakefield** [contentful/contentful-import#15]
After updating assets, `contentful-import` appears to send all process asset requests at once causing the client to become rate-limited which in turn breaks the import.

**Comment by Khaledgarbaya** [comment]
hi @lwakefield ,

all the request are going through the same client which is rate limited, [here](https://github.com/contentful/contentful-sdk-core/blob/master/lib/wrap-http-client.js#L28) , we have plans to improve that but the asset requests are not sent at once. but if you have a big amount of assets you could hit the hourly rate limit.

**Comment by lwakefield** [comment]
If the hourly rate is set at 216000 as per the docs, it seems fairly unlikely that we are hitting that. Is there anyway to tell?

Regardless of where the rate-limiting is coming from, it would be nice if the importer could wait and retry instead of crashing. Is this on the roadmap by any chance?

**Comment by Khaledgarbaya** [comment]
Yes, we have that on the roadmap to make the import tool more tolerant about errors.

**Comment by jesseweed** [comment]
Any updates on this, or a good work-around? I'm currently stuck with the import tool _always_ throwing "429 rate limit exceeded" error after processing assets. Content type import successfully, asset process fine, but then it errors out after processing assets (after only about 3mins) before ever getting to importing entries. The space I'm trying to import has 207 assets, 160 entries and 15 content types, so there's definitely no reason it should be hitting a rate limit.

At a minimum I think this script needs to be able handle these errors without crashing, so we can handle it and possibly retry. Our code is super basic and looks something like this:

```
import(options)
.then((output) => {
// do something
})
.catch((err) => {
// handle errors
})
```

However, the app crashes before it ever reaches the catch, so there's I have way to handle the error at the application level.

Any direction on steps to get this working correctly? We have several spaces we need to sync on a regular basis and manual updating is not an option, so really need to figure out a solution to this, any ideas to get passed the would be great.

Thanks!

**Comment by jesseweed** [comment]
Hey, just to update my progress. I cloned the repo locally and pulled in @zanzamar's changes from https://github.com/contentful/contentful-import/pull/8 and https://github.com/contentful/contentful-batch-libs/pull/80 and it seems to have solved my rate limit issue.

This is okay for now as a temporary solution, but it would be great of those PR's could get merged soon and save a lot of headache.

Thanks!

**Comment by Khaledgarbaya** [comment]
hey @jesseweed I merged that for now, a new version should be released when the ci finishes the build.

**Comment by jesseweed** [comment]
Awesome, thanks for getting that in @Khaledgarbaya!

**Comment by scottsandersdev** [comment]
@Khaledgarbaya can this param be added to documentation? Also, looking through the source code, it looks like rate-limit can be passed to this tool... is that correct?

**Comment by Khaledgarbaya** [comment]
Hi we are working really hard on fixing all of these issues, expect a major release soon with more stability, retry on server errors and better ratelimiting. It gonna be awesome ! 
until then I won't be able to update the docs because some of the stuff we have already is subject to change.

Cheers,
Khaled

**Comment by axe312ger** [comment]
The last major release should have fixed this issue. Please open a new issue when this problem still occurs.
